### ISSUE TITLE
TODO rules

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/stencil-eslint#1]
Pending rule:

- [ ] public apis must be documented
- [ ] order of properties/methods following the stencil’s style guide
- [ ] validation of the component’s tag
- [ ] validation of the component’s class name
- [ ] enforce tag-name prefix
- [ ] @Element() type must be HTML{tag-name}Element
- [ ] mutation of Prop()
- [ ] side mutation of objects and arrays in @State() and @Prop()
- [ ] prefer <Host> vs returning array in render()
- [ ] always prefer Host

**Comment by manucorporat** [comment]
Help wanted!

**Comment by Serabe** [comment]
For arrays, we can suggest using `ReadonlyArray<T>` instead of `T[]` and for objects we have the mapped type `Readonly<T>`. That way, the checker can be simplified.

**Comment by manucorporat** [comment]
That's a great idea @Serabe ! and easy enough to implement

**Comment by chimon2000** [comment]
@manucorporat would it be better to split these rules out to individual issues?  I see some have been added but the list hasn't been updated.

**Comment by d0whc3r** [comment]
I just created a pull request with some rules and tests
https://github.com/ionic-team/stencil-eslint/pull/2
